### ISSUE TITLE
A question about agent.py

### ISSUE THREAD

**Issue by 2345as** [Cernewein/heating-RL-agent#18]
Dear author:

Hi, there! I'm trying to reimplement your code. While doing so, I encountered a problem. It seems that agent.py is not accessed anywhere, is my understanding right?

I'll appreciate it if you could spare some time to answer.

**Comment by 2345as** [comment]
By the way, is the class `BasicBuilding` missing in `environment.py`?

**Comment by Cernewein** [comment]
Hi,

Indeed you understand this right. agent.py is actually a legacy file which contains an instance of a simple q-learning agent (no deep learning here).
It wasn't updated to take into account the changes to environment.py (this is why there is still a basicBuilding instance). You can either discard the file completly and only look at ddpg.py and dqn.py or try to modify it by replacing basicBuilding by building.

Best

**Comment by 2345as** [comment]
Sure, after asking these questions on github, I found that other parts of your code do not need to use these files, and it has already run out according to your method. Your model is very excellent, I will citing&nbsp; your article later, and the training results for different periods of data are very good. Here again, thank you very much for sharing this code




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cernewein/heating-RL-agent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月2日(星期二) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Cernewein/heating-RL-agent] A question about agent.py (Issue #18)





 
Hi,
 
Indeed you understand this right. agent;py is actually a legacy file which contains an instance of a simple q-learning agent (no deep learning here).
 It wasn't updated to take into account the changes to environment.py. You can either discard the file completly and only look at ddpg.py and dqn.py or try to modify it by replacing basicBuilding by building.
 
Best
